# Generated by Django 5.2.8 on 2025-11-09 16:53

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(db_index=True, max_length=10, verbose_name='Номер документа')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата издания')),
                ('document_title', models.CharField(db_index=True, max_length=800, verbose_name='Название документа')),
                ('signed_by', models.CharField(max_length=255, verbose_name='Кем подписан документ')),
                ('responsible_executor', models.CharField(max_length=255, null=True, verbose_name='Ответственный исполнитель')),
                ('transferred_to_execution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому передан (ответственный за исполнение приказа)')),
                ('transferred_for_storage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому передано на хранение')),
                ('heraldic_blank_number', models.CharField(max_length=20, null=True, verbose_name='Номер гербового бланка')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('scan', models.FileField(blank=True, null=True, upload_to=orders.models.order_scan_upload_to, verbose_name='Скан приказа')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
    ]
