# Generated by Django 5.1.4 on 2024-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='№ п/п')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('issue_date', models.DateField(verbose_name='Дата издания')),
                ('document_title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('signed_by', models.CharField(max_length=150, verbose_name='Кем подписан документ')),
                ('responsible_executor', models.CharField(max_length=150, verbose_name='Ответственный исполнитель')),
                ('transferred_to_execution', models.CharField(max_length=150, verbose_name='Кому передан (ответственный за исполнение приказа)')),
                ('transferred_for_storage', models.CharField(max_length=150, verbose_name='Кому передано на хранение')),
                ('heraldic_blank_number', models.CharField(blank=True, max_length=20, verbose_name='Номер гербового бланка')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
