# Generated by Django 5.2.8 on 2025-11-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doc_type',
            field=models.CharField(choices=[('order', 'Приказ'), ('decree', 'Распоряжение')], db_index=True, default='order', max_length=10, verbose_name='Вид документа'),
        ),
    ]
