# Generated by Django 5.1.4 on 2024-12-23 07:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_file', models.FileField(blank=True, upload_to='media/orders_scan')),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2024, 12, 23, 7, 37, 2, 626754))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
