# Generated by Django 5.1.4 on 2024-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_scan_delete_scanorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='heraldic_blank_number',
            field=models.CharField(max_length=20, verbose_name='Номер гербового бланка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transferred_for_storage',
            field=models.CharField(blank=True, max_length=150, verbose_name='Кому передано на хранение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transferred_to_execution',
            field=models.CharField(blank=True, max_length=150, verbose_name='Кому передан (ответственный за исполнение приказа)'),
        ),
    ]
