# Generated by Django 5.1.4 on 2024-12-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='document_number',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='responsible_executor',
            field=models.CharField(max_length=255, verbose_name='Ответственный исполнитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='signed_by',
            field=models.CharField(max_length=255, verbose_name='Кем подписан документ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transferred_for_storage',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кому передано на хранение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transferred_to_execution',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кому передан (ответственный за исполнение приказа)'),
        ),
    ]
