# Generated by Django 5.1.4 on 2024-12-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='document_title',
            field=models.CharField(db_index=True, max_length=800, verbose_name='Название документа'),
        ),
    ]
