# Generated by Django 5.1.4 on 2024-12-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transferred_for_storage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому передано на хранение'),
        ),
    ]
