# Generated by Django 5.1.4 on 2024-12-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_transferred_for_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transferred_to_execution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому передан (ответственный за исполнение приказа)'),
        ),
    ]
