# Generated by Django 5.1.4 on 2024-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_transferred_to_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='responsible_executor',
            field=models.CharField(max_length=255, null=True, verbose_name='Ответственный исполнитель'),
        ),
    ]
