# Generated by Django 5.1.4 on 2024-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_responsible_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='heraldic_blank_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер гербового бланка'),
        ),
    ]
