# Generated by Django 5.2.4 on 2025-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_heraldic_blank_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата издания'),
        ),
    ]
